//! Auto-generated protobuf types for rdesk.
//!
//! This module includes code generated by `prost-build` from the `.proto`
//! definitions located in the `proto/` directory at the workspace root.

/// Types from `rdesk.message` -- session-level protocol messages including
/// media frames, input events, file transfer, and control messages.
pub mod message {
    include!(concat!(env!("OUT_DIR"), "/rdesk.message.rs"));
}

/// Types from `rdesk.rendezvous` -- signaling/rendezvous protocol messages
/// for peer registration, hole punching, relay negotiation, and NAT detection.
pub mod rendezvous {
    include!(concat!(env!("OUT_DIR"), "/rdesk.rendezvous.rs"));
}
